### ISSUE TITLE
TotalAmount:Set the total amount of tokens issued.

### ISSUE THREAD

**Issue by bandot-org** [bandotorg/Bandot#2]
Set the total amount of tokens issued.

**Comment by BeDreamCoder** [comment]
see [0ba0977d0e](https://github.com/bandotorg/Bandot/blob/0ba0977d0edec020e0f0bc21b36da0019b3732ab/runtime/src/bancor.rs#L29)

**Comment by wuminzhe** [comment]
What does token.rs stand for? @BeDreamCoder

**Comment by skyh24** [comment]
@wuminzhe it's the bdt token  issued by ourselves
